version: '3.4'

services:
  folderscanner:
    image: ${DOCKER_REGISTRY-}folderscanner
    ports:
     - 5005:8080
    build:
      context: .
      dockerfile: FolderScanner/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=http://*:8080
